### ISSUE TITLE
Lack of attacker on other_death

### ISSUE THREAD

**Issue by osztenkurden** [LaihoE/demoparser#10]
Hey,
Not sure if its a matter of a new demo format, but for  me at least other_death event looks like that:
`    {
        "attackerblind": false,
        "event_name": "other_death",
        "headshot": false,
        "noscope": false,
        "otherid": 304,
        "othertype": "chicken",
        "penetrated": 0,
        "thrusmoke": false,
        "tick": 575,
        "weapon": "glock",
        "weapon_fauxitemid": "",
        "weapon_itemid": "5689486849",
        "weapon_originalowner_xuid": ""
    }`

With no attacker steamid information.

**Comment by LaihoE** [comment]
This is the same bug as #12  . These events were missing user/attacker fields. Should be fixed in 0.4.0

**Comment by LaihoE** [comment]
As 0.4.0 is out now I'm closing this. Feel free to re-open if something is still wrong.
