### ISSUE TITLE
How to get a player index?

### ISSUE THREAD

**Issue by maxpain** [LaihoE/demoparser#103]
We need something like this:
https://github.com/akiver/cs-demo-analyzer/blob/main/pkg/api/analyzer.go#L307C1-L307C76

**Comment by LaihoE** [comment]
Use the entity_id or user_id fields

**Comment by maxpain** [comment]
@LaihoE Actually, I need to get the index of players in demo viewer
<img width="576" alt="image" src="https://github.com/LaihoE/demoparser/assets/5875582/245fae9e-f873-4778-b371-26316226a42a">

**Comment by LaihoE** [comment]
JS
```JavaScript
let gameEndTick = Math.max(...parseEvent(filePath,"round_end").map(x => x.tick))
let players = parseTicks(filePath, ["user_id", "team_name"], [gameEndTick])
let ctPlayers = players.filter(x => x.team_name == "CT")
let tPlayers = players.filter(x => x.team_name == "TERRORIST")

ctPlayers.sort((a,b) => a.user_id - b.user_id)
tPlayers.sort((a,b) => a.user_id - b.user_id)

slots = []
slots.push(...ctPlayers)
slots.push(...tPlayers)

for (let i = 1; i < slots.length; i++){
    slots[i]["slot_num"] = i
}
console.log(slots)
```

Python
```Python
max_tick = parser.parse_event("round_end")["tick"].max()
df = parser.parse_ticks(["user_id", "team_name"], ticks=[max_tick])


ct_players = df[df["team_name"] == "CT"]
t_players = df[df["team_name"] == "TERRORIST"]

ct_players = ct_players.sort_values(by="user_id")
t_players = t_players.sort_values(by="user_id")

all_players = pd.concat((ct_players, t_players),ignore_index=True)
all_players.insert(0, "slot", range(1, len(all_players) + 1))

print(all_players)
```

**Comment by maxpain** [comment]
@LaihoE Does it handle player disconnects and player substitution during the match?

**Comment by LaihoE** [comment]
just replace the wanted_tick with the tick you are interested in. Also I don't think the slots change during the game.

**Comment by maxpain** [comment]
@LaihoE neither `user_id` nor `entity_id` didn't work as a sort property :(

**Comment by ChetdeJong** [comment]
@maxpain Hi, just checked this. Works fine for me with user_id, but not in every demo.

There's typo in JS snippet above 

this one works as expected
```
for (let i = 0; i < slots.length; i++) {
	let current_ind = i + 1;
	slots[i]["slot_num"] = current_ind;
}
```

The problem with this is that they switch sides throughout the game and in overtimes, but their slots dont get changed.
And for some reason in some demos even when players start as T their slots are counted if they were CT. 
So in one demo I tested it works as expected, in other it doesnt.

Not sure what to do about it for now.

I hope that Valve just bring back command to select player with SteamID as in CSGO 😄

**Comment by ChetdeJong** [comment]
@maxpain  

I checked quite a few demos, same not consistent result.

I think for now the most reliable way is to get slots from `game state integration` while playing demo e.g. with `allplayers_id` component. 
https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration

Result below. 
0 here is 1, so have to shift them by 1 and replace 10 by 0 to get needed key.
You can see in this demo they start as T, but get keys as they were CT.

@LaihoE is there no way to get observer slot from demo itself?

```
{
  "allplayers": {
    "76561198012872053": {
      "name": "huNter",
      "observer_slot": 0,
      "team": "T"
    },
    "76561197999825422": {
      "name": "nexa",
      "observer_slot": 1,
      "team": "T"
    },
    "76561197998926770": {
      "name": "HooXi",
      "observer_slot": 2,
      "team": "T"
    },
    "76561198074762801": {
      "name": "m0NESY",
      "observer_slot": 3,
      "team": "T"
    },
    "76561198041683378": {
      "name": "NiKo",
      "observer_slot": 4,
      "team": "T"
    },
    "76561198246607476": {
      "name": "b1t",
      "observer_slot": 5,
      "team": "CT"
    },
    "76561198176878303": {
      "name": "jL",
      "observer_slot": 6,
      "team": "CT"
    },
    "76561199063068840": {
      "name": "w0nderful",
      "observer_slot": 7,
      "team": "CT"
    },
    "76561198013243326": {
      "name": "Aleksib",
      "observer_slot": 8,
      "team": "CT"
    },
    "76561198050250233": {
      "name": "iM",
      "observer_slot": 9,
      "team": "CT"
    }
  }
}
```

**Comment by LaihoE** [comment]
@ChetdeJong Is it maybe failing in pro games and working in mm? Maybe they do some odd stuff in the pro demo? Anyway I have not seen anything in the demo that would look like "observer_slot". I think this should be possible but I just don't know where to look :(

**Comment by ChetdeJong** [comment]
@maxpain in recent update they added `spec_lock_to_accountid` and some more spectator commands. Is that what you needed?

**Comment by LaihoE** [comment]
To me this seems like we don't need this anymore as you can now search by player name/id? @ChetdeJong @maxpain

**Comment by ChetdeJong** [comment]
> To me this seems like we don't need this anymore as you can now search by player name/id? @ChetdeJong @maxpain

ye, that's exactly what I use now, just like in csgo

**Comment by LaihoE** [comment]
Closing for now.

**Comment by lukepolo** [comment]
@ChetdeJong do you have an example?

**Comment by lukepolo** [comment]
im testing with
```
 let players = parseTicks(demoPath, ["user_id", "team_name"], [tick])
    let ctPlayers = players.filter(x => x.team_name == "CT")
    let tPlayers = players.filter(x => x.team_name == "TERRORIST")
    
    ctPlayers.sort((a,b) => a.user_id - b.user_id)
    tPlayers.sort((a,b) => a.user_id - b.user_id)
    
    let slots = []
    slots.push(...ctPlayers)
    slots.push(...tPlayers)
    
    for (let i = 1; i < slots.length; i++){
        slots[i]["slot_num"] = i
    }

    const slot = slots.find((slot) => {
        return slot.name === player;
    });

```

**Comment by ChetdeJong** [comment]
@lukepolo 

Hi, what's your end goal? 
Do you need exactly spectator (observer) key or some id in general to switch to needed player?

Last time I checked the method that was discussed here didnt work consistently, so you can't get spectator key from it. If your goal is just to switch player you can use `spec_lock_to_accountid` with steamid or you can use `spec_player` with userid + 1 e.g. userid is 6, so you do `spec_player 7` to switch to that player. Or you can use GSI if that works for you

**Comment by lukepolo** [comment]
spec_lock_to_accountid Seems perfect ,I’ll give it a go . I’ll share my script here soon , using this to generate  a mp4 of all their kills from a single round

**Comment by lukepolo** [comment]
yeah unfortunately this doesn't work , at least on linux

**Comment by lukepolo** [comment]
ill try that later today, going to leave this here too 


https://gist.github.com/lukepolo/dac28b1d323a42d885092f8b51187cd7
