### ISSUE TITLE
num_player_alive_t / num_player_alive_ct bugged first round

### ISSUE THREAD

**Issue by Tirre** [LaihoE/demoparser#104]
The fields 'num_player_alive_ct' and 'num_player_alive_t' seems to be bugged. 
The first round of the game is always filled with the value 63 for both T and CT.

Additionally, is this prop supposed to count the amount of players alive at any given tick? Or does it show how many were alive at the end of the round? The data confirms the latter. If so, I think that can be explained further in the README as I had misunderstood it intially.

![bild](https://github.com/LaihoE/demoparser/assets/4738551/4e81e0b8-e4ac-457a-b61b-f34a83eab163).

**Comment by LaihoE** [comment]
Yeah this one is just misleading and you are better off manually checking for "is_alive" for the players. I'm removing the prop from the list in the README.
(the prop comes from the engine so fixing the issue is also tricky)
