### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Tirre** [LaihoE/demoparser#105]
Just wanted to report on the player_colors that I mapped myself while watching the demo and checking the values.
Maybe add this somewhere under the readme (similar with the RoundWinReason and HitGroups) as seen in #19 so people can re-use them as necessary.

| Color | Number |
| --- | --- |
| BLUE | 0 |
| GREEN| 1 |
| YELLOW | 2 |
| ORANGE | 3 |
| PURPLE | 4 |

Also for the hitgroups, I believe hitgroup=0 (GENERIC) and hitgroup=10 (GEAR) also exists.
I have never seen hitgroup=10 been targetted, but hitgroup=0 is used for grenades.

| Hitgroup | Translation |
| --- | --- |
| GENERIC | 0 |
| HEAD | 1 |
| CHEST | 2 |
|STOMACH | 3 |
|LEFTARM | 4 |
|RIGHTARM | 5 |
| LEFTLEG | 6 |
| RIGHTLEG | 7 |
| GEAR | 10 |

**Comment by LaihoE** [comment]
https://github.com/LaihoE/demoparser/pull/206

Thanks!

These are now directly translated to readable versions.
