### ISSUE TITLE
Weapon User Velocity is null

### ISSUE THREAD

**Issue by dbalders** [LaihoE/demoparser#109]
User velocity on the weapon fire event seems to be showing null now. Believe it was working before.

v0.17.2

<img width="279" alt="Screenshot 2024-01-11 at 9 13 06 PM" src="https://github.com/LaihoE/demoparser/assets/4715098/a5ee03df-6f69-4765-9719-61fbde661e03">

**Comment by Tirre** [comment]
Ran into the same issue.
v0.15.3 extracts it properly, but v0.16.0 does not. Did not find anything obvious when comparing tags (https://github.com/LaihoE/demoparser/compare/v0.15.3...v0.16.0) but possibly mismatch between npm tags and Github tags?

**Comment by LaihoE** [comment]
https://github.com/LaihoE/demoparser/pull/204

Should be fixed here :sweat_smile: sorry for the delay!
