### ISSUE TITLE
Any plans to fix builds for linux?

### ISSUE THREAD

**Issue by Rishats** [LaihoE/demoparser#119]
Hello! First of all thank you for the parser! 😊 I'm wondering if there is any update on Linux builds? I saw there were errors in the GitHub actions for the build of version 0.17, and it seems unresolved. Do you have any understanding of what the problem might be? 🤔

```
6.049 ERROR: Could not find a version that satisfies the requirement demoparser2==0.17.0 (from versions: 0.15.2, 0.15.3, 0.16.0, 0.16.1)
6.049 ERROR: No matching distribution found for demoparser2==0.17.0
```

**Comment by LaihoE** [comment]
The build should now be fine. The original problem was that in 0.17.0 I added parsing of voice data, but I never managed to build that on linux so voice parsing is on hold for now.

0.16.0 Should be fine, the only missing feature should be the voice data.

**Comment by LaihoE** [comment]
0.18.0 works fine for linux
