### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lobanov-vitaliy** [LaihoE/demoparser#12]
How can I get information in **player_blind** event about who threw the grenade and who it blinded?

```js
{
  blind_duration: 3.5758512020111084,
  entityid: 602,
  event_name: 'player_blind',
  tick: 124537
}
```

Now it's only **entityid** and it's not clear which player and which team he's from, and who threw the grenade.

Another question is how to find out the time when the event occurred

**Comment by LaihoE** [comment]
This is the same bug as #10 . These events were missing user/attacker fields. Should be fixed in 0.4.0

**Comment by LaihoE** [comment]
Entityid actually refers to the grenade and not to the player. You can map to this id in parse_grenades(). Anyway I think for your use-case it seems like the fixed attacker and user fields will do the trick.

**Comment by lobanov-vitaliy** [comment]
Thanks i will wait 0.4.0 )

**Comment by LaihoE** [comment]
As 0.4.0 is out now I'm closing this. Feel free to re-open if something is still wrong.
