### ISSUE TITLE
Need add dependency of "protobuf-codegen" in csgoproto.

### ISSUE THREAD

**Issue by jaredliu2018** [LaihoE/demoparser#124]
I'm using it in rust directly and the csgoproto project can't compile. I think "protobuf-codegen" should be added to Cargo.toml.

**Comment by jaredliu2018** [comment]
I put demoparse into my project as a submodule. When I build csgoproto I got error below:
error[E0433]: failed to resolve: use of undeclared crate or module `protobuf_codegen`
 --> demoparser\src\csgoproto\src\main.rs:2:5
  |
2 |     protobuf_codegen::Codegen::new()
  |     ^^^^^^^^^^^^^^^^ use of undeclared crate or module `protobuf_codegen`

**Comment by LaihoE** [comment]
Maybe you are right, won't hurt to add it. Do you want to make a PR or want me to do it?

**Comment by jaredliu2018** [comment]
I notice you've add it already. so I'll close this issue. Thanks!
