### ISSUE TITLE
Value dmg_health of -2147483648

### ISSUE THREAD

**Issue by osztenkurden** [LaihoE/demoparser#13]
Hey,

It happened only once for me, on the below demo on tick 102656 player_hurt event happens with dmg_health value of -2147483648

https://drive.google.com/file/d/1Ka8xO-9MoKC1h7zKSXd7sNlku5nL5dw4/view?usp=sharing

Btw I'd like to ask a few questions about Source 2 demo parsing overall, to better understand it in a deep way, is there any way we could chat (ex discord), I'd just have a couple of questions.

**Comment by LaihoE** [comment]
Seems like a bug in the demo. I'm quite sure this will get fixed as the game comes out of beta. If not then maybe do some cleaning.

discord: Laiho#2448
