### ISSUE TITLE
Error when trying to get the table of results by event parse_event("round_end")

### ISSUE THREAD

**Issue by sml153** [LaihoE/demoparser#130]
Hi, thank you so much for your work)

I am a novice developer and if the error is not in lib but in "my hands", I apologize in advance.

When I try to get the table of results using your example, I get the error "TypeError: list indices must be integers or slices, not str". Everything worked before. Also, if I change the argument from round_end to player_death, I get the table with all fields without errors.

My code (repeats your example):
```
parser = DemoParser("path_to_demo")
max_tick = parser.parse_event("round_end")["tick"].max()

wanted_fields = ["kills_total", "assists_total", "deaths_total", "ace_rounds_total", "4k_rounds_total", "3k_rounds_total", "damage_total", 'team_rounds_total', 'team_clan_name']
df = parser.parse_ticks(wanted_fields, player=["X", "Y"], ticks=[max_tick])
```
[The example I'm referring to](https://github.com/LaihoE/demoparser/blob/main/examples/scoreboard/main.py)

**Comment by LaihoE** [comment]
Could there be something with the 
```Python
max_tick = parser.parse_event("round_end")["tick"].max()
```
New demos currently are missing round_end events (working on it atm) that could be causing the problem.

Maybe you could check if this is returning any events at all:
```Python
df = parser.parse_event("round_end")
```

and maybe check an old demo from over 1 month ago.

**Comment by sml153** [comment]
On older demos it works as expected. Really the problem is in the new demo.
_Maybe you could check if this is returning any events at all: df = parser.parse_event("round_end")_
New demos return a empty list: []
Old demos return correct list with this params:
```
    legacy                      message  nomusic  player_count  reason    tick  winner
0        0  #SFUI_Notice_Terrorists_Win        0            16       9    4502       2
```
And if I add a parameter for slice ['tick'], I get end-of-round ticks

demos: https://drive.google.com/file/d/1m5Ee0-zYzBtF5VVTK_3bm7H3EBwbQmpp/view?usp=sharing
or hltv: [old](https://www.hltv.org/matches/2368432/g2-vs-aurora-cct-2023-online-finals-5) [new](https://www.hltv.org/matches/2369746/faze-vs-eternal-fire-pgl-cs2-major-copenhagen-2024-europe-rmr-a)

**Comment by jaredliu2018** [comment]
same problem. can't get "round_end" events. parser.parse_event("round_end") return empty.

**Comment by sml153** [comment]
@LaihoE thank you for fix that :)
