### ISSUE TITLE
node package has yarn.lock and package-lock.json

### ISSUE THREAD

**Issue by switz** [LaihoE/demoparser#131]
There should probably only be 1, which package manager do you prefer?

**Comment by LaihoE** [comment]
I don't really care which one, tbh I don't know what 90% of the files there are for as they have been autogenerated at some point. Feel free to remove anything that isn't needed. If it builds with "yarn build" then the file is probably not needed.

**Comment by LaihoE** [comment]
Ehh closing this for now, maybe the rust bindings somehow use both?
