### ISSUE TITLE
Ticks class/type instance name

### ISSUE THREAD

**Issue by 4nything** [LaihoE/demoparser#14]
Hello!!

I hope u to be fine. I'm using this lib, that is so good, but i found that updating the version the names had changed, is this now the correct name?

![image](https://github.com/LaihoE/demoparser/assets/71851923/b8f8ba92-fb87-46b3-bb07-6845dc9d2c69)

**Comment by LaihoE** [comment]
This does not look good... what version is this?

**Comment by 4nything** [comment]
is the last one 0.4.1!

**Comment by LaihoE** [comment]
odd... what is the input?

**Comment by 4nything** [comment]
first get the events "round_start" and "round_end", then used the method parseTicks(path, <array with those props>), and build each round filtering the ticks with round_start tick and round_end tick, just that

**Comment by LaihoE** [comment]
ok nvm, I was able to reproduce. The problem is with the "per round stats" and "total stats". Unfortunately I found that these are bugged (same problem with the officical demo viewer ("playdemo" command in cs2). 

I will fix this soon but unfortunately current demos give sometimes wrong values for these fields.

**Comment by 4nything** [comment]
thank you for your fast response!

**Comment by LaihoE** [comment]
![image](https://github.com/LaihoE/demoparser/assets/80683769/8cc21be5-c62f-42e7-9494-12e6e70b8127)
Here is example :(

**Comment by 4nything** [comment]
ohhh i see, is retrieving nothing in some values, thats cause the beta right? hope be fixed asap from valve then

**Comment by 4nything** [comment]
Sorry for ask this here, is there a doc to get what matches the hitgroup number? i see only 1, 2, 3, but i don't know what refers to

**Comment by LaihoE** [comment]
I don't know. A quick google gave me this: 

HEAD=1
CHEST=2
STOMACH=3
LEFTARM=4	
RIGHTARM=5
LEFTLEG=6
RIGHTLEG=7

Don't know if its right.

It's a good question. Feel free to open a new issue if you have similar questions so that others might find it.
