### ISSUE TITLE
Getting round information on an player_death event

### ISSUE THREAD

**Issue by DandrewsDev** [LaihoE/demoparser#15]
Im looking to get the current round at the time of the player death

Previously this was done by passing a rounds=True param to the parse_event function.
parser.parse_event("player_death", rounds=True, ...

However this no longer appears to work. I also tried passing total_rounds_played as a prop. But seemed to have no effect. 

Doesnt seem like something that would have been removed intentionally, just can't seem to figure out what Im doing wrong here.

**Comment by LaihoE** [comment]
```Python
df = parser.parse_event("player_hurt", player_extra=["total_rounds_played", "team_rounds_total"])
```
This should give you fields "user_total_rounds_played", "user_team_rounds_total", "attacker_total_rounds_played" and "attacker_team_rounds_total". Now this is a bit odd as user_total_rounds_played and attacker_total_rounds_played gives you the same value so eventually I want to add something like:

```Python
df = parser.parse_event("player_hurt", non_player_or_something=["total_rounds_played", "team_rounds_total"])
```
That should let you ask for values which don't need to be gotten from the perspective of a player. This is especially important for events that don't refer to players at all (maybe this is your case atm?). Regarding what happens to "team" props: It will always give you both teams values by default.

I'm around 2/3 done with implementing this.

**Comment by DandrewsDev** [comment]
Okay yea this does give me some information about the rounds played and looks like a totally workable solution for now.
`player_extra=["total_rounds_played", "team_rounds_total"]`

Does make me wonder, what happens if a user disconnects, a couple rounds are played, and the user rejoins. Could the user total, and attacker total differ? Or is this just a count of all the rounds that have happened but provided from a users perspective?

I'll keep an eye out for that work on non player based information. Most the data Im grabbing is from the players perspective. But the rounds and some others are more of a "State of the game" at the time of that event.

**Comment by LaihoE** [comment]
Maybe ill rename it to state instead of "other".
```Python
event_df = parser.parse_event("player_death", player=["X", "Y"], state=["total_rounds_played"])
```

**Comment by DandrewsDev** [comment]
I tested out the latest 0.5.0 and yea that works great. Thank you for putting in a fix for this so quickly!

Also thanks for that additional info. I figured that was the case for how that round count from the players perspective not changing but thank you for confirming.
