### ISSUE TITLE
feat: support querying of m_aimPunchAngle & m_aimPunchAngleVel

### ISSUE THREAD

**Issue by mannall** [LaihoE/demoparser#152]
Currently demoparser doesn't support querying of the weapon aimpunch angle/velocity properties. I suspect because they are vec3's this makes them quite annoying to deal with? I managed to implement this by duplicating the logic for pitch/yaw (i.e. fn find_pitch_or_yaw -> fn find_aim_punch_pitch_or_yaw) and making it a custom property, but I guess this is quite lousy.

**Comment by LaihoE** [comment]
quite the opposite, duplicating the logic for pitch/yaw would be the better option. Its faster this way and working with arrays inside dataframes in python is especially painful. 

If you want to submit a pr then we can merge it.

**Comment by LaihoE** [comment]
Fixed here: https://github.com/LaihoE/demoparser/pull/205
