### ISSUE TITLE
Date of match

### ISSUE THREAD

**Issue by maxpain** [LaihoE/demoparser#153]
Hello. Is it possible to get the date of a match from a demo?

**Comment by LaihoE** [comment]
nope :( best you can do is check the game version from the header.

**Comment by ndorigatti** [comment]
sorry if i re-open this, but why the value of 'demo_file_stamp' is always 'PBDEMS2\x00'?

Maybe it is just a problem of file decoding? The demo time should be available in the dem file (at least valve can read it someway)

Am i right and we just don't know how to read it or is a missing value?

**Comment by ndorigatti** [comment]
ok, thank you! I'm new to parsing this data, have you any clue on how to read the info? seems a binary file, is it a protopuf file too?

**Comment by Paul2708** [comment]
Sorry for bumping this again, but is there yet a solution to this issue? As reported by @ndorigatti, it seems possible to extract the date.
@ndorigatti, do you still happen to know how you decoded the demo file?

**Comment by ndorigatti** [comment]
@Paul2708 helllo, i just did a dirty stuff on dem.info file, then gave up
