### ISSUE TITLE
parsePlayerInfo performance

### ISSUE THREAD

**Issue by ChetdeJong** [LaihoE/demoparser#154]
Hi,

I'm trying to get players info from number of demos with `parsePlayerInfo`
However I noticed it's much less performant, than parsing some event say `round_announce_match_start` and then one tick from it, to get the same data.

I'm not sure if there's issue with parser or just it is what it is.

This is the result I get when parsing 44 demos:

parsePlayerInfo: 13.306s
parseEventAndTick: 6.574s

I'm running JS script on 6 worker threads and demos are on SSD.

Script:
[demoParserTest.zip](https://github.com/LaihoE/demoparser/files/14755160/demoParserTest.zip)

**Comment by LaihoE** [comment]
Ah you are right, the parsePlayerInfo is unreasonably slow. This could be fixed but my plan is to move away from these separate functions into simple game events. So you would use something like "player_connect" event in the future.

**Comment by LaihoE** [comment]
https://github.com/LaihoE/demoparser/pull/201

player_info does not parse entities anymore and should be very fast now.
