### ISSUE TITLE
Convars for Nodejs

### ISSUE THREAD

**Issue by zek** [LaihoE/demoparser#156]
Can we expose parse_convars function in NodeJS?

**Comment by LaihoE** [comment]
The convars should now be emitted as a game event: "server_cvar". The idea was to move these seperate functions to game events.

**Comment by zek** [comment]
Thank you! I didn't know that. 

Any option to see all available eventNames, playerExtra, otherExtra?

**Comment by LaihoE** [comment]
events can be listed by listGameEvents(), as they can vary on some demos. The playerExtra and otherExtra are the ones in the README.md

**Comment by zek** [comment]
Thank you!
