### ISSUE TITLE
`weapon_paint_seed` should be an integer

### ISSUE THREAD

**Issue by thwonghin** [LaihoE/demoparser#158]
For some reason `weapon_paint_seed` prop has floating points in the output of `parse_ticks`, while it should be an integer. I don't know if I should round up or round down to have the correct value.

**Comment by LaihoE** [comment]
Its a bit wonky atm, but it should not have any decimal values if it works correctly. ie value should be 370.0 --> 370

**Comment by LaihoE** [comment]
ah I was mixing it up with another thing. Are you sure it really is an integer? I think its really a float but people just round it?

**Comment by thwonghin** [comment]
> ah I was mixing it up with another thing. Are you sure it really is an integer? I think its really a float but people just round it?

Honesly I don't really know what's the internal data representation of a paint seed.

It looks like people always see it as an integer (between 0-1000). I googled a bit and find this article about [seed distrubution](https://blog.csfloat.com/analysis-of-float-value-and-paint-seed-distribution-in-cs-go/#paint-seed-distribution), the values it plots do not have decimal places.

And multiple skin sites also display it as an integer.

**Comment by LaihoE** [comment]
I think you are right. Maybe it should be an int after all. I just find it odd how the parser works without failing even with incorrect decoding of the value. I'll have to take a look at it.

**Comment by LaihoE** [comment]
https://github.com/LaihoE/demoparser/pull/200

Fixed here.
