### ISSUE TITLE
Missing player skins: question about `parse_player_end_msg` method

### ISSUE THREAD

**Issue by thwonghin** [LaihoE/demoparser#159]
When I'm reading [`parse_player_end_msg`](https://github.com/LaihoE/demoparser/blob/main/src/parser/src/second_pass/other_netmessages.rs#L85C69-L85C70) method, it is the only place to populate the `.skins` list, which only happens at the end of the match. However, the skins could be different at both sides (CT/T).... so I'm assuming it is missing one side of the data.

I've parsed couple of demos and confirm the list only has one side of the data.

It would be great if the skin list can be populated with both sides of the data somehow, maybe populate the list per round, deduplicate by each player's team number.

**Comment by LaihoE** [comment]
Also generally I think it would be better to have these things as game events and not separate functions for each thing,

**Comment by LaihoE** [comment]
Now that we have the item_purchase event you should use that instead
