### ISSUE TITLE
team_clan_name

### ISSUE THREAD

**Issue by Nettarr** [LaihoE/demoparser#170]
i am getting issues with team_clan_name for demos after the new update

**Comment by LaihoE** [comment]
Do you have a demo I could check out?

**Comment by Nettarr** [comment]
yeah but i cant post it here anywhere i can send it to you

**Comment by Nettarr** [comment]
https://drive.google.com/file/d/1tk0DIG8h1149J6PE1QZWUGP5dQOg9Qg0/view?usp=drive_link

**Comment by Nettarr** [comment]
problem is that i need the clan names and none of the teams seem to have any

**Comment by LaihoE** [comment]
With new demos it seems to work, closing for now.
