### ISSUE TITLE
wasm build fails because `sys` module not found

### ISSUE THREAD

**Issue by BeepIsla** [LaihoE/demoparser#171]
Hey,

I am trying to compile the wasm version myself but when using `cd src/wasm && ./build.sh` the build fails with `error[E0583]: file not found for module 'sys'`. I have made sure `wasm-pack` is up-to-date (0.12.1).

**Comment by LaihoE** [comment]
Could you try with latest version?

**Comment by BeepIsla** [comment]
Works now, thanks for the quick fix!
