### ISSUE TITLE
parse_event("round_end") causes memory error on some (new) demos

### ISSUE THREAD

**Issue by martin1896** [LaihoE/demoparser#172]
Hi,

I am using your library to get some data from our weekly monday 5v5 scrimmage match demos. This monday I encountered the problem that `parse_event("round_end")["tick"].max()` runs out of memory and leads to following error: `memory allocation of 167712024240 bytes failed`.

Older demos still work great and the function delivers the requested tick without problems. Both new and old demo can be viewed ingame.

I use exactly the code from your scoreboard example, so it should be easy to reproduce the error.

Maybe it's related to the last big update from May 23? 

I uploaded both (working and broken demo) here: https://drive.google.com/drive/folders/1gRkln-f3OrMRkQXquPGVYKwTAyBgVBoK

Thanks a lot for this great library!

**Comment by LaihoE** [comment]
Try updating to newest version

**Comment by martin1896** [comment]
Now it works. Sorry for wasting your time :) Thanks a lot!
