### ISSUE TITLE
Giving wrong argument type to `player` parameter in `parse_event` causes panic.

### ISSUE THREAD

**Issue by JanEricNitschke** [LaihoE/demoparser#174]
Giving the wrong argument type to any of the kwargs causes a panic instead of raising a python error.

See: https://github.com/LaihoE/demoparser/blob/main/src/python/src/lib.rs#L949

**Comment by LaihoE** [comment]
Yeah the python binding code could use some cleaning up 😄. Do you want to give it a try? Should be quite simple (feel free to modify the entire function)

**Comment by JanEricNitschke** [comment]
Fixed by https://github.com/LaihoE/demoparser/pull/180
