### ISSUE TITLE
Add e2e test for python version into CI

### ISSUE THREAD

**Issue by JanEricNitschke** [LaihoE/demoparser#177]
I think currently this part is not actually being tested in the CI, right?

Would also give an explanation of how to do it locally during development.

**Comment by LaihoE** [comment]
Originally everything was tested from both python and node, but as this caused double effort the tests were moved back to Rust. The plan was to make some simple tests for the bindings only (not for each prop and event etc.), but never had the time to.

**Comment by JanEricNitschke** [comment]
Makes sense. Then i would add some tests that call each method with valid and invalid arguments and check the returned types.
