### ISSUE TITLE
`parse_voice` uses `PyValueError` while all other functions use `Exception`

### ISSUE THREAD

**Issue by JanEricNitschke** [LaihoE/demoparser#182]
Is there a reason why `parse_voice` has a `PyValueError::new_err(format!("{e}"))` [here](https://github.com/LaihoE/demoparser/blob/main/src/python/src/lib.rs#L725C34-L725C71), while all the other functions have `Exception::new_err(format!("{e}"))` ([see](https://github.com/LaihoE/demoparser/blob/main/src/python/src/lib.rs#L155))

I also noticed that all function have this code block in common:

```
        let mmap = match create_mmap(self.path.clone()) {
            Ok(mmap) => mmap,
            Err(e) => {
                return Err(Exception::new_err(format!(
                    "{}. File name: {}",
                    e,
                    self.path.clone()
                )))
            }
        };
        let settings = ParserInputs {
            wanted_players: vec![],
            wanted_player_props: vec![],
            wanted_other_props: vec![],
            wanted_events: vec![],
            wanted_ticks: vec![],
            real_name_to_og_name: AHashMap::default(),
            parse_ents: false,
            parse_projectiles: false,
            only_header: false,
            count_props: false,
            only_convars: false,
            huffman_lookup_table: &vec![],
            order_by_steamid: false,
        };
        let mut parser = Parser::new(settings, false);
        let output = match parser.parse_demo(&mmap) {
            Ok(output) => output,
            Err(e) => return Err(PyValueError::new_err(format!("{e}"))),
        };
```

Would it make sense to move this to the constructor? Then one could also more easily allow different way to pass the file, like directly passing a file handle or something like that (see [discord](https://discord.com/channels/1150401692211359774/1150401692211359777/1255972995676246106))

**Comment by LaihoE** [comment]
Ah yes of course :+1:. Don't know why it is like that.

**Comment by JanEricNitschke** [comment]
The second part seems to not be completely trivial.

The part from here: `let settings = ParserInputs {` can be moved into the constructor because some of the methods allow passing different thins to the ParserInputs.

There are also some very smal differences in the `huffman_lookup_table` inputs. One has this line `let arc_huf = Arc::new(huf);` before the `huf` is passed there. Although most of the other functions also call it `arc_huf` despite it not being arc.

**Comment by JanEricNitschke** [comment]
Also, from the commented out code. It seems that this part used to be in the constructor. Not sure why it isnt anymore.
