### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by 4nything** [LaihoE/demoparser#19]
Hi LaihoE!

I open this cause some topic we discussed previously about the numbers and the names of hitgroups. I'll leave here the names you gave me: 

HEAD=1
CHEST=2
STOMACH=3
LEFTARM=4
RIGHTARM=5
LEFTLEG=6
RIGHTLEG=7

Also, I wanted to ask you about the round end reasons, do you have the descriptions? If you have them, can you leave here? In case you don't i can look for them comparing the matches. 

Thank you a lot!

**Comment by LaihoE** [comment]
Not sure about these. You can probably use "message" to help.
<pre>    legacy                      message  nomusic  player_count  reason   tick  winner
0        0         #SFUI_Notice_CTs_Win        0            20       8  11112       3
1        0         #SFUI_Notice_CTs_Win        0            20       8  18448       3
2        0         #SFUI_Notice_CTs_Win        0            20       8  23496       3
3        0    #SFUI_Notice_Target_Saved        1            20      12  32584       3
4        0         #SFUI_Notice_CTs_Win        0            20       8  38999       3
5        0         #SFUI_Notice_CTs_Win        0            20       8  43124       3
6        0         #SFUI_Notice_CTs_Win        0            20       8  51625       3
7        0         #SFUI_Notice_CTs_Win        0            20       8  59561       3
8        0         #SFUI_Notice_CTs_Win        0            20       8  65914       3
9        0         #SFUI_Notice_CTs_Win        0            20       8  70358       3
10       0  #SFUI_Notice_Terrorists_Win        0            20       9  77131       2
11       0         #SFUI_Notice_CTs_Win        0            20       8  82000       3
12       0  #SFUI_Notice_Terrorists_Win        0            20       9  86511       2
13       0  #SFUI_Notice_Terrorists_Win        0            20       9  93171       2
</pre>

**Comment by Tirre** [comment]
Just wanted to add for context. Extracted this information from another CSGO parser project a few years back.
The numbers might be different for CS2 but the defusal maps win reasons seems to be the same at least (1,7,8,9)
var roundWinReasons = {
	1: 'Bomb Exploded', // t win
	4: 'TerroristsEscaped', // t win?
	5: 'CTStoppedEscape', // ct win?
	6: 'TerroristsStopped', //ct win?
	7: 'Bomb Defused', // ct win
	8: 'Terrorists Killed', // ct win
	9: 'Counter-Terrorists Killed', // t win
	10: 'Round Draw', //round draw
	12: 'Target Saved', // ct win
	17: 'Terrorists Surrender', // ct win
	18: 'Counter-Terrorists Surrender', // t win
	19: 'TerroristsPlanted', //??
	20: 'CTsReachedHostage' //??
}

**Comment by LaihoE** [comment]
https://github.com/LaihoE/demoparser/pull/206

These are now directly translated to readable versions.
