### ISSUE TITLE
entity_visible events are empty

### ISSUE THREAD

**Issue by bukson** [LaihoE/demoparser#194]
Hello.

According to documentation, there is an event called entity_visible https://cs2.poggu.me/dumped-data/game-events/#entity_visible

PRoblem is, for every demo I parse there are no such events.

Should I enable some console option to store those events, or it is a bug?

**Comment by LaihoE** [comment]
Many of the event listed here are not part of the demos. I'm not sure it is even possible to enable them trough any setting?

Anyhow if you are looking for visibility between players you can do something like this:
```Python
from demoparser2 import DemoParser

parser = DemoParser("path_to_demo.dem")
ticks_df = parser.parse_ticks(["approximate_spotted_by"])
```
The event would most likely just listen to changes in this value. But it is not perfect and the event would likely not be any better. Exactly determining when a player spots another is a very complicated process and not something the game keeps track off in some kind of even/variable as far as I know.

**Comment by LaihoE** [comment]
Closing for now as I don't think there is much that can be done
