### ISSUE TITLE
pitchyaw missing/eyeangles aren't available in demoparser2 pip package

### ISSUE THREAD

**Issue by IOExceptional** [LaihoE/demoparser#2]
Is there a particular reason these aren't available?

**Comment by LaihoE** [comment]
added pitch/yaw to 0.0.9. Unfortunately there is no good way for me to check if the yaw/pitch are correct without being able to check the values in game :(

**Comment by IOExceptional** [comment]
I believe you can still use the setpos command to verify a location + eyeangles, unless you mean you don't have CS2 access?

**Comment by LaihoE** [comment]
Yeah I don't have CS2 access 😢

**Comment by LaihoE** [comment]
I'll happily fix this if you get me a demo + correct yaw/pitch at a given tick :smiley:

**Comment by LaihoE** [comment]
Checked against demo viewer and values seems OK. closing
