### ISSUE TITLE
MVPs missing from Player Data

### ISSUE THREAD

**Issue by DandrewsDev** [LaihoE/demoparser#21]
Currently unable to pull MVPs for players. Not sure if its as simple as adding the code below. Or if there is some technical issue with pulling that data from CS2 demos I dont know of.

`"CCSPlayerPawn.m_iMVPs" => PropType::Player,`
And
`"mvps" => "CCSPlayerPawn.m_iMVPs",`

**Comment by LaihoE** [comment]
added in 0.5.1. You were very close, the prop lives in the players controller so the name is: CCSPlayerController.m_iMVPs. Otherwise correct.

**Comment by DandrewsDev** [comment]
Awesome, thanks for getting that added. 

I'll have to get a local dev env setup so I can test things like that and make a PR next time.
