### ISSUE TITLE
Considerations to improve the rust code

### ISSUE THREAD

**Issue by Lol3rrr** [LaihoE/demoparser#218]
Hey,
just wanna start this issue with saying that reading trough this repo and the code, really helped me work on my own parser implementation and gaining somewhat of an understanding of the structure of demo files.
However I noticed some patterns that are not very "rusty" and make the code harder to read IMO, would you be open to accepting a PR with some improvements in this area?

# Examples
- In the first pass sendtables file the [get_propinfo](https://github.com/LaihoE/demoparser/blob/ca6ff92d3e681df3969d2892f8f912c32921f83c/src/parser/src/first_pass/sendtables.rs#L457) function could early return in/after the first match and then not need the conditional further down.
- [this condition](https://github.com/LaihoE/demoparser/blob/ca6ff92d3e681df3969d2892f8f912c32921f83c/src/parser/src/first_pass/sendtables.rs#L220) could be moved into the match above

**Comment by LaihoE** [comment]
Yes, the code could use some work and your examples seem reasonable. PR:s are very welcome.
