### ISSUE TITLE
active_weapon_name is null when the player is holding a nade or the bomb

### ISSUE THREAD

**Issue by Yesber** [LaihoE/demoparser#22]
It would be nice if it also switched to the different grenade types and the C4. There is no way to keep track of what the player is holding in their hands otherwise.

**Comment by LaihoE** [comment]
Thanks for bringing this up, was not aware of this happening. I will likely fix this in the same release with the "inventory" feature.

**Comment by LaihoE** [comment]
I think this should be fixed now? There was some odd stuff happening with active_weapon_name

**Comment by Yesber** [comment]
Looks good, I've poked at it a bit and I have nothing to report 👍
