### ISSUE TITLE
Wrong `user_id` field in some demos

### ISSUE THREAD

**Issue by ChetdeJong** [LaihoE/demoparser#221]
In some demos [(example)](https://www.hltv.org/matches/2376253/parivision-vs-spirit-academy-cct-season-2-europe-series-13) when querying `player_death` events I get wrong `user_id` field e.g. `65282`. 

It is not demo problem since if I query same events with [another parser ](https://github.com/markus-wa/demoinfocs-golang) it gets `user_id` correctly.

test code:
```js
import { parseEvents } from "@laihoe/demoparser2"; // v0.33.1
import path from "path";

const demoPath = path.resolve('./parivision-vs-spirit-academy-m3-dust2.dem');
const data = parseEvents(demoPath, ['player_death'], ['user_id']).map(e => `Attacker Name: ${e.attacker_name} Attacker UserID: ${e.attacker_user_id}`);
console.log(data.join('\n'));
```

**Comment by LaihoE** [comment]
Thanks for bringing this up. Fixed: https://github.com/LaihoE/demoparser/pull/225
