### ISSUE TITLE
Close Demo File

### ISSUE THREAD

**Issue by Chris-F5** [LaihoE/demoparser#222]
Using the python bindings, once a demo file is opened there is (as far as I can tell) no way of closing it. The README python example does not close the demo file. I can see no close function in `src/python/demoparser2.pyi`.

I have a script which opens one demo file after another in a sequence like the following:
```
loop:
    fetch demo file from external hard disk
    parser = demoparser2.DemoParser(fname)
    do some processing on the demo file
    # I would like to close the demo file here. Something like `parser.close()`
```
As this runs, I can watch the number of open file descriptors increase with `lsof`.

**Comment by LaihoE** [comment]
🤔 Are you storing the "parser" objects? I would expect the files to be closed when the object is destroyed but I may be wrong.

**Comment by Chris-F5** [comment]
I was not storing the parser objects. I had a closer look at this and you are right, the files do get closed when the DemoParser object gets destroyed.

My script was failing because the python garbage collector was being too slow to cleanup the DemoParser objects. My filesystem would become full with demo files before the garbage collector closed any of the culprit files. I managed to fix it by explicitly destroying the parser object with `del parser`, thereby forcing the garbage collector to destroy the object and close the files immediately.

**Comment by LaihoE** [comment]
del parser seems like a good enough solution for now.
