### ISSUE TITLE
where do you get the full list of fields of events to extract from the demo?

### ISSUE THREAD

**Issue by t0mkee** [LaihoE/demoparser#223]
for example  `parser.parse_event("player_hurt")`, it didn't appear in the readme docs, so I searched the repo for `player_hurt` and because I couldn't find it I'm guessing it's contained in the demo file itself. I'd like to know where I can get these additional fields in the demo because they don't appear in the docs.

**Comment by t0mkee** [comment]
[never mind, found it here ](https://cs2.poggu.me/dumped-data/game-events/#:~:text=All%20the%20game%20events%20parsed%20from:%20csgo/pak01_dir.vpk/resource/game.gameevents.)

**Comment by LaihoE** [comment]
```parser.list_game_events()``` gives you a list off all events in the demo.
