### ISSUE TITLE
Find players on T and CT for round or at tick?

### ISSUE THREAD

**Issue by bkushigian** [LaihoE/demoparser#229]
I want to figure out who is T and CT, either at round start or at a particular tick, either would work. I'm not seeing this data anywhere in any of the properties/tables. Is there a way to derive this from the properties that exist?

**Comment by LaihoE** [comment]
Maybe you are looking for the "team_name" property?

**Comment by bkushigian** [comment]
Ah yup, there it is. Tired eyes I guess...thank you!
