### ISSUE TITLE
Time in demo

### ISSUE THREAD

**Issue by LaihoE** [LaihoE/demoparser#23]
Currently unsure how to get the "time" in the demo. Props often refer to something like "seconds since demo started" or similar but nothing seems to work. Using ticks (both demo tick and in-game tick) also seem to give slightly incorrect values. pls help if anyone knows more about this. I think hackers in csgo used something like this: ```gpGlobals->curtime``` but how could this be gotten in the demo?

**Comment by 4nything** [comment]
i could get it by tick / 64, idk why is not in 128, is weird

**Comment by LaihoE** [comment]
What do you mean by "kills times"? Cause it should be tick/64 but I remember it giving me the wrong answer 🤔

**Comment by 4nything** [comment]
Actually, i use tick/64 for everything and retrieves correct times. By "kills times", i mean the second that the kill happened

**Comment by LaihoE** [comment]
"game_time" prop added in 0.7.0 for this.
