### ISSUE TITLE
comp_rank on last tick shows rank before match start

### ISSUE THREAD

**Issue by andruszkow** [LaihoE/demoparser#24]
The comp_rank property doesn't change. For the old match making ranks you would have rankOld and rankNew int's.

The goal is to deduct the cs rating before match end, and the cs rating after match end.

I struggle to locate the event that either:

- Contains the new ratings, post-match, for comp_rank_type = 11 (premier)
- Contains the data for potential win/loss of rating (pre-game data?)

Are you able to describe where to find this?

**Comment by LaihoE** [comment]
Thank you for bringing this up. Had forgotten this as premier was only introduced lately.

in 0.6.0:
I've added 3 new fields: rank_if_win, rank_if_loss, rank_if_tie
Added a event: "rank_update" that should look something like this:

<pre>   num_wins  rank_change  rank_new  rank_old  rank_type_id      user_name       user_steamid
0        12       -120.0      9879      9999            11      Player1  7656111111111111
1         6          0.0         0         0            11             Player2  7656111111111112
2         4          0.0         0         0            11             Player3  7656111111111113
3         5          0.0         0         0            11             Player4  7656111111111114
4         7          0.0         0         0            11             Player5  7656111111111115
5         9          0.0         0         0            11             Player6  7656111111111116
6         8          0.0         0         0            11             Player7  7656111111111117
7         9          0.0         0         0            11             Player8  7656111111111118
8        10          0.0     11711         0            11             Player9  7656111111111119
9         6          0.0         0         0            11             Player10 76561111111111110
</pre>
or similar if using node.
