### ISSUE TITLE
Lack of rank_update and Almost 70MB on npm

### ISSUE THREAD

**Issue by osztenkurden** [LaihoE/demoparser#28]
Hey!
Npm package weighs almost 70mbs due to some json files, not sure if intended.
Also rank_update event isnt part of the listGameEvents. Also not sure if that should be there given its not game event but I think its also not in readme

**Comment by LaihoE** [comment]
Hi,
Oops didnt know NPM was pushing those... deleted now in 0.8.1. Also regarding rank_update: yes I think it should be part of list_game_events so I added it there. Preferably the user would not know if the game event is "real" or not.

**Comment by osztenkurden** [comment]
Thx <3
