### ISSUE TITLE
[Question] Adding an Example Demo File

### ISSUE THREAD

**Issue by TalkAboutOdd** [LaihoE/demoparser#3]
Would it be possible to add a demo file you've been using for testing for those of us who also don't have the beta?

**Comment by LaihoE** [comment]
I don't have beta myself either :smile: . Markus hosted some, see this issue: https://github.com/markus-wa/demoinfocs-golang/pull/384. Also not sure if all of them work or what type of demos they even are. At least some of them should work :laughing:

**Comment by LaihoE** [comment]
See this :laughing: https://github.com/markus-wa/demoinfocs-golang/pull/384. (sorry Markus if you didn't want me to share this 😬)
