### ISSUE TITLE
entity_id

### ISSUE THREAD

**Issue by 1mpulse** [LaihoE/demoparser#34]
Is it possible to add output of "entity_id" information to event parsing? of all players or add a function to get extended information about a player by his steamID64 on a tick.

**Comment by LaihoE** [comment]
Could you tell me a bit more about what you are doing?

**Comment by 1mpulse** [comment]
I'm parsing the "player_death" event and I need to know the entity_id of the attacker.

**Comment by LaihoE** [comment]
So just like 
```
df = parser.parse_event("player_death", player=["entity_id"])
```
Sure why not. Will add to next release

**Comment by 1mpulse** [comment]
`let event_json = parseEvents(Path, ["round_start", "player_death"], ["entity_id"], ["total_rounds_played"]);`

`Error: UnknownPropName("entity_id")`

nodeJS

**Comment by 1mpulse** [comment]
> Sure why not. Will add to next release

ohhh, tyy

**Comment by 1mpulse** [comment]
only I need the entity_id of both the victim and the attacker.

**Comment by LaihoE** [comment]
Yes this will add fields: "user_entity_id" and "attacker_entity_id"

**Comment by 500pls** [comment]
@LaihoE This change is also very important for me. I'm ready to donate to you if you update quickly

**Comment by LaihoE** [comment]
in 0.9.1 you can now get this:
```JavaScript
let events_json = parseEvent("path_to_demo.dem", "player_death", ["entity_id"])
console.log(events_json[0])
```

{
  assistedflash: false,
  assister_entity_id: null,
  assister_name: null,
  assister_steamid: null,
  attacker_entity_id: 159,
  attacker_name: 'player1',
  attacker_steamid: '765611981111111111',
  attackerblind: false,
  distance: 25.807619094848633,
  dmg_armor: 0,
  dmg_health: 110,
  dominated: 0,
  event_name: 'player_death',
  headshot: true,
  hitgroup: 1,
  noreplay: false,
  noscope: false,
  penetrated: 0,
  revenge: 0,
  thrusmoke: false,
  tick: 3052,
  user_entity_id: 191,
  user_name: 'player2',
  user_steamid: '765611982222222222',
  weapon: 'famas',
  weapon_fauxitemid: '',
  weapon_itemid: '26567681461',
  weapon_originalowner_xuid: '',
  wipe: 0
}

**Comment by LaihoE** [comment]
> @LaihoE This change is also very important for me. I'm ready to donate to you if you update quickly

Thank you, but not taking donations atm :smile:

**Comment by 1mpulse** [comment]
> in 0.9.1 you can now get this:
> 
> ```js
> let events_json = parseEvent("path_to_demo.dem", "player_death", ["entity_id"])
> console.log(events_json[0])
> ```
> 
> { assistedflash: false, assister_entity_id: null, assister_name: null, assister_steamid: null, attacker_entity_id: 159, attacker_name: 'player1', attacker_steamid: '765611981111111111', attackerblind: false, distance: 25.807619094848633, dmg_armor: 0, dmg_health: 110, dominated: 0, event_name: 'player_death', headshot: true, hitgroup: 1, noreplay: false, noscope: false, penetrated: 0, revenge: 0, thrusmoke: false, tick: 3052, user_entity_id: 191, user_name: 'player2', user_steamid: '765611982222222222', weapon: 'famas', weapon_fauxitemid: '', weapon_itemid: '26567681461', weapon_originalowner_xuid: '', wipe: 0 }

Awesome, thank you.
