### ISSUE TITLE
Allow passing buffer instead of path

### ISSUE THREAD

**Issue by LaihoE** [LaihoE/demoparser#37]

**Comment by switz** [comment]
I would be open to implementing this myself and sending a PR, would you mind pointing me in some direction?

**Comment by LaihoE** [comment]
In the node/src/lib.rs
(build it by running "yarn build" in node/)


This needs to be changed to
```Rust
#[napi]
pub fn parse_header(path: String) -> Result<Value> {
  let file = File::open(path.clone())?;
  let mmap = unsafe { MmapOptions::new().map(&file)? };
}
```


Something like this:
```Rust
use napi::Either;

#[napi]
pub fn parse_header(path_or_buf: Either<String, Buffer>) -> Result<Value> {

 let bytes = match path_or_buf {
    Either::A(path) => {
      let file = File::open(path.clone())?;
      let mmap = unsafe { MmapOptions::new().map(&file)? };
      BytesVariant::Mmap(mmap)
    }
    Either::B(buf) => BytesVariant::Vec(buf.into()),
  };
 ```
Might want to create a new function for this so that you dont need to copypaste it to every function.

**Comment by LaihoE** [comment]
Sorry if you are still working on this. I added it in 0.14.0:

https://github.com/LaihoE/demoparser/commit/477340a9b64cad3ec8d2401ec97465e726163581

**Comment by LaihoE** [comment]
Assume this is implemented now, re-open/new issue if something regarding this

**Comment by maxpain** [comment]
@LaihoE Did you forget to regenerate typescript definitions?
https://github.com/LaihoE/demoparser/blob/af896248e401fe7b046d179d606f064acdc01e97/src/node/index.d.ts#L11
