### ISSUE TITLE
SteamID is number instead of string

### ISSUE THREAD

**Issue by osztenkurden** [LaihoE/demoparser#4]
Hey,

When parsing a CS2 demo in NodeJS, SteamID field is being returned as a number instead of string - it's an issue, because JS can not work with this kind of big integers, so every SteamID is rounded and has zero at the end:
![image](https://github.com/LaihoE/demoparser/assets/25458209/18145ee5-f351-41e7-974b-4ab293250f78)

**Comment by LaihoE** [comment]
Thanks for raising this. Steamid is a string from 0.1.6 forward.
