### ISSUE TITLE
ADR Calculation

### ISSUE THREAD

**Issue by UROjQ6r80p** [LaihoE/demoparser#51]
Does anybody know why ADR is not calculated correctly?
I'm trying to calculate ADR for this match: https://www.hltv.org/matches/2367004/spirit-vs-9ine-cct-north-europe-series-8

According to HLTV the ADR for Mirage should be:
![image](https://github.com/LaihoE/demoparser/assets/90694123/6e0fe87f-b0c5-4248-bc9d-4816471cce6f)

but mine is too high, even if i clamp damage to max 100 it is incorrect.
```
{
  donk: 117.05882352941177,
  zont1x: 99.82352941176471,
  KEi: 75.88235294117646,
  ArtFr0st: 63.529411764705884,
  hades: 144.35294117647058,
  Goofy: 84.23529411764706,
  magixx: 88.76470588235294,
  chopper: 109.11764705882354,
  Kylar: 48.05882352941177,
  mynio: 63.411764705882355
}
```

```
const { parseEvent } = require('@laihoe/demoparser2');

const DEMO_FILE = 'spirit-vs-9ine-m2-mirage.dem';

damageActions = parseEvent(DEMO_FILE, 'player_hurt', ['team_name'], [
    'total_rounds_played',
    'is_warmup_period'
]);

const filtered = damageActions
    .filter(e => e.is_warmup_period === false)
    .filter(e => e.attacker_team_name !== e.user_team_name);

maxRound = Math.max(...damageActions.map(o => o.total_rounds_played));

const stats = {}
filtered.forEach(e => {
    if (e.attacker_name) {
        stats[e.attacker_name] = stats[e.attacker_name] + e.dmg_health || e.dmg_health
    }
});
for (prop in stats) {
    stats[prop] = stats[prop] / maxRound;
}
console.log(stats);
```

**Comment by researchersec** [comment]
Try like this

`
const { parseEvent } = require('@laihoe/demoparser2');

const DEMO_FILE = 'spirit-vs-9ine-m2-mirage.dem';

damageActions = parseEvent(DEMO_FILE, 'player_hurt', ['team_name'], [
    'total_rounds_played',
    'is_warmup_period'
]);

const filtered = damageActions
    .filter(e => e.is_warmup_period === false)
    .filter(e => e.attacker_team_name !== e.user_team_name);

const stats = {};

filtered.forEach(e => {
    if (e.attacker_name) {
        if (!stats[e.attacker_name]) {
            stats[e.attacker_name] = { damage: 0, rounds: 0 };
        }
        stats[e.attacker_name].damage += e.dmg_health;
        stats[e.attacker_name].rounds++;
    }
});

for (prop in stats) {
    stats[prop].adr = stats[prop].damage / stats[prop].rounds;
}

console.log(stats);
`

**Comment by LaihoE** [comment]
I tried a bunch of stuff but can't quite get it to line up no matter what.

In 0.13.0 you can do this:

```JavaScript
var {parseEvent, parseTicks} = require('./index');


const pathToDemo = "/home/laiho/Documents/demos/cs2/pro/d.dem";

let gameEndTick = Math.max(...parseEvent(pathToDemo,"round_end").map(x => x.tick))

let fields = ["total_rounds_played", "damage_total"]
let players = parseTicks(pathToDemo, fields, [gameEndTick])

for (let i = 0; i < players.length; i++){
    let player = players[i]
    console.log(player.name, player.damage_total / player.total_rounds_played);
}
```
Gives this that is very close but not quite:
```
ArtFr0st 45.705882352941174
donk 98.3529411764706
Kylar 44.294117647058826
KEi 50.411764705882355
magixx 72.6470588235294
zont1x 92
chopper 92.58823529411765
Goofy 69.41176470588235
hades 94.6470588235294
mynio 55.94117647058823
```

Btw clamping to 100 isn't quite enough. I think you would need to check the players health and make sure the damage isn't more than the players total health. For example:

Player hurt 45 dmg and victim has 12 hp --> only 12 "real" dmg done. (this is what the total_damage field should do)

**Comment by UROjQ6r80p** [comment]
@LaihoE 
thanks for help,
Yup, I tried demoinfo-golang after creating this topic, and the key is exactly as you said `total_damage` here, the rest is just checking: `is_match_started`, `is_freeze_period`, and `is_warmup_period`, excluding team dmg etc. but even then some demos are broken, in this demo player "hades" does not match, the rest does after checking those flags.

btw. did something reset in npm page? I think it included full description of the parser on the page but now it's blank here: https://www.npmjs.com/package/@laihoe/demoparser2

**Comment by LaihoE** [comment]
I don't think the npm page ever had anything interesting. What type of description are you looking for? 

https://github.com/LaihoE/demoparser/blob/main/examples
https://github.com/LaihoE/demoparser/blob/main/documentation

Is all I can think of.

**Comment by UROjQ6r80p** [comment]
@LaihoE I think you're right, I had an impression that npm page had same README as github page for some reason.

**Comment by researchersec** [comment]
Did you ever solve this?

**Comment by UROjQ6r80p** [comment]
> Did you ever solve this? After getting a headshot in first round my total damage was exactly cut of at 100 so there must be something with your theory. In the old game if you headshotted with AWP you would get around 400 dmg added.

@researchersec If you use `total_damage` instead of `dmg_health` it should show correct damage for the ADR calculation.

But in general if I want to get ADR calculated like HLTV does, relying on either `total_damage` or `dmg_health` shows incorrect results. I needed to parse `player_hurt` event.
In demoinfo-golang I had to get damage done by the attacker, get starting health of the victim to whom the damage is done, and then the formula is like:
```
// pseudo code
dmg += attacker.hp_taken > victim.health ? victim.health : attacker.hp_taken`
```
so if attacker does headshot for 400 dmg, but victim has only 34 hp, the damage should be 34.

I couldn't achieve what I want in this library because the `player_hurt` event shows `health` after the damage (i dont think it's a bug, but I needed health before the damage), so if attacker made 140 damage, it shows victim has 0 health. `damage_total` is described as "Aggregate stats (updates one time per round)" so i guess it's not the same as the damage from the `player_hurt` event.
```
{
    armor: 50,
    attacker_name: 'kyxsan',
    attacker_steamid: '76561198057282432',
    dmg_armor: 15,
    dmg_health: 104,
    event_name: 'player_hurt',
    health: 0, // this is health AFTER the damage
    hitgroup: 1,
    tick: 9075,
    user_name: 'arT',
    user_steamid: '76561198043769572',
    weapon: 'ak47'
  }
```

@LaihoE is it possible to get a `health` of victim before the damage in the `player_hurt` event?

**Comment by LaihoE** [comment]
I think the newest version already does what you want. The order of events/entities was recently changed.   
```let result = parseEvent("path", ["health"])``` Should give the health before the kill/hurt happen

**Comment by UROjQ6r80p** [comment]
That's great @LaihoE 

@researchersec In general it's rather impossible to always get same ADR calculated as on HLTV page. They update their stats live during the match (https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration) because they have access to it directly from event organizers. Demos are often missing few damages/events. I doubt HLTV is parsing their own demos after the match. The closest I was able to calculate is based on the `player_hurt` events.
