### ISSUE TITLE
Add the ability to retrieve the modelname of an entity

### ISSUE THREAD

**Issue by 0xGabrielel** [LaihoE/demoparser#52]
It would be lovely to be able to retrieve the correct model used by an entity in a specific demo, as an example players using agent skins etc..

something like https://github.com/saul/demofile/blob/d815a88e98698a849326b845c959261a5c7d4d2f/src/entities/baseentity.ts#L68C1-L80

**Comment by LaihoE** [comment]
I took a look into stringtables and I think they are not there anymore (in cs2). Entities do seem to have a new field like this:

"CCSPlayerPawn.CBodyComponentBaseAnimGraph.m_hModel = U64(13181005211767972979)

(a field that is decoded as a u64). But how this number should be interpreted i don't know :/

**Comment by LaihoE** [comment]
@0xGabrielel I added the prop "agent_skin" to 0.15.0. Is there anything else that could be interesting?

**Comment by 0xGabrielel** [comment]
closing issue as it was done: added in ver 0.15.0
