### ISSUE TITLE
'clan_name' Blank When Using parseTicks

### ISSUE THREAD

**Issue by dbalders** [LaihoE/demoparser#57]
Error: When parsing ticks for player data using parseTicks, the clan_name attribute is always blank instead of the team name.

Demo: https://www.hltv.org/matches/2367592/complexity-vs-m80-thunderpick-world-championship-2023

Reproduce: `let clanNameData = parseTicks(filePath, ["clan_name"], [singleTick])`

<img width="343" alt="Screenshot 2023-10-31 at 2 31 51 PM" src="https://github.com/LaihoE/demoparser/assets/4715098/299fbe12-1c42-4f3c-8f58-b425ec33e693">

**Comment by LaihoE** [comment]
seems like the other clan_name prop is not supported anymore. I removed it from the README. Use "team_clan_name" instead.

**Comment by dbalders** [comment]
Gotcha, thanks!
