### ISSUE TITLE
parseGrenade not getting all grenade types

### ISSUE THREAD

**Issue by dbalders** [LaihoE/demoparser#58]
Error: the parseGrenade function seems to only get smokes, decoys, and molotovs. Missing flashbangs, hegrenades, and potentially incendiary.

Demo: https://www.hltv.org/matches/2367592/complexity-vs-m80-thunderpick-world-championship-2023

Reproduce:

```
let grenadeThrown = parseGrenades(filePath);

for (let i = 0; i < grenadeThrown.length; i++) {
    if (grenadeThrown[i].grenade_type !== "smoke"
        && grenadeThrown[i].grenade_type !== "molotov"
        && grenadeThrown[i].grenade_type !== "decoy") {
        console.log('here')
    }
}
```

The console log never triggers. It never has a type that isn't one of those 3.

**Comment by LaihoE** [comment]
What version are you on?

**Comment by dbalders** [comment]
I'm on 0.13.0

**Comment by LaihoE** [comment]
Could you double check? I just created a fresh node project with demoparser2==0.12.0 and I'm getting a bunch of "here" prints

**Comment by LaihoE** [comment]
Also are you using the demos you linked? quite recently they fixed something in the demos.

**Comment by dbalders** [comment]
Crap, im sorry. Forgot I had hardcoded an older demo when testing something else so it was using that, not the one I linked. It looks like it is working now. Thanks for checking, my fault.

**Comment by LaihoE** [comment]
no worries!
