### ISSUE TITLE
no game events in Esportal demos

### ISSUE THREAD

**Issue by jhaikonen** [LaihoE/demoparser#63]
Tried to parse game events from demo that was recorded on esportal match (esportal.com) and it did not register any game events besides server_cvar. 

Tried with demoinfocs-golang, and it did register bomb plants, defuses and explodes for example, but not player_death or player_hurt

tried with nodejs, and let eventNames = listGameEvents(pathToDemo)

**Comment by jhaikonen** [comment]
seems that this version gets the events https://github.com/markus-wa/demoinfocs-golang/tree/s2-fake-CMsgSource1LegacyGameEventList

**Comment by LaihoE** [comment]
Added fallback event list in 0.14.0. Should fix this.

**Comment by osztenkurden** [comment]
@LaihoE Hey, it appears that demos are enabled in CSTV from today, and Im having similiar issue with demo of game I played today. Using 0.14.1, and the only events showing are: `[ 'rank_update', 'server_cvar', 'hltv_versioninfo' ]`. https://drive.google.com/file/d/1haTUPszGdwwYK6riuXDucVYhZhA97lk4/view?usp=sharing

**Comment by LaihoE** [comment]
Seems like the new MM demos are completely missing game events. The esportal problem was regarding missing a message in the beginning of the demo leading to events not being parsed properly.

**Comment by osztenkurden** [comment]
Should I open new issue then? Also what is in those demos, if no game events when they are 80MB in size

**Comment by LaihoE** [comment]
Sure you could open a new issue as its not connected to this. I looked at the demo and couldn't really found anything new. Anyway game events are tiny in size compared to entities. probably like 1% of demo size comes from game events.

**Comment by osztenkurden** [comment]
I opened a new one to keep this thread clean

**Comment by LaihoE** [comment]
Assume this is fixed, re-open if needed
