### ISSUE TITLE
No Game Events in demos

### ISSUE THREAD

**Issue by osztenkurden** [LaihoE/demoparser#67]
It appears that demos served from CSTV do not have any game events in them. The only accessible events are: [ 'rank_update', 'server_cvar', 'hltv_versioninfo' ]. Example: https://drive.google.com/file/d/1haTUPszGdwwYK6riuXDucVYhZhA97lk4/view?usp=sharing

**Comment by LaihoE** [comment]
I looked at the demo with the in game demo viewer and it is clearly missing events as there are no kills  appearing in the top right, bomb plants are not displayed on the screen etc. Seems like the ingame viewer is also depending on the events so this seem like more of a bug than anything they planned to do.

**Comment by LaihoE** [comment]
This should be fixed with the newest patch?

**Comment by osztenkurden** [comment]
Yep, it is. Im closing
