### ISSUE TITLE
parseHeader always returns an empty array

### ISSUE THREAD

**Issue by MHase** [LaihoE/demoparser#7]
I've noticed that method `parseHeader` always returns `[]`
is this intentional for now? I need to find map name and that's why it's crucial for me 😃 

if needed there is my latest demo
http://replay182.valve.net/730/003637360004291363051_0801419002.dem.bz2

**Comment by LaihoE** [comment]
Thanks for bringing this up, fixed in 0.2.1

**Comment by MHase** [comment]
works like a charm ♥️
