### ISSUE TITLE
hostage_rescued event missing player data (user_player_steamid)

### ISSUE THREAD

**Issue by tuesi** [LaihoE/demoparser#82]
Using node js when parsing hostage_rescued event no player data is shown.

var hostage = parseEvent(demoPath, "hostage_rescued", ["player_steamid", "time"], ["total_rounds_played", "team_name", "num_player_alive_ct", "num_player_alive_t"]);

<img width="220" alt="image" src="https://github.com/LaihoE/demoparser/assets/32371856/8d622b80-22e0-4360-b225-2c79532e4d84">

**Comment by LaihoE** [comment]
Checked a new demo and it seems to work fine, maybe this was something with old demos? closing for now.
