### ISSUE TITLE
OutOfBitsError for scoreboard example (NodeJS) "damage_total" field, using faceit demo

### ISSUE THREAD

**Issue by agrislaicans** [LaihoE/demoparser#83]
Hi. I tried your scoreboard example [https://github.com/LaihoE/demoparser/tree/main/examples/scoreboard](url) 
First I copy/pasted the code and everything was working fine but when I changed field "score" to "damage_total", it gives me OutOfBitsError. Same goes for utility_damage_total field. I tried 2 different demos - One was working and the other one wasn't.. As far as I tested, many other fields are working fine.
Here's matchroom for the failed one: [https://www.faceit.com/en/cs2/room/1-a5779c42-44e7-4b7d-b960-237c1da4c55e](url)

Code:

    var {parseEvent, parseTicks} = require('@laihoe/demoparser2');
    
    const pathToDemo = "demo.dem"

    let gameEndTick = Math.max(...parseEvent(pathToDemo,"round_end").map(x => x.tick))

    let fields = ["kills_total", "deaths_total", "mvps", "headshot_kills_total", "ace_rounds_total", "damage_total"]
    let scoreboard = parseTicks(pathToDemo, fields, [gameEndTick])

    console.dir(scoreboard);

Result:
`
Error: OutOfBitsError
    at /home/user/www/demo/app.js:20:22
    ....
`

**Comment by LaihoE** [comment]
https://github.com/LaihoE/demoparser/commit/6577b3ac80e535d2900f28fbadd55e334fabf6a6
Should have fixed this. Will be part of next release.
