### ISSUE TITLE
attacker is null in player_blind event

### ISSUE THREAD

**Issue by willbex** [LaihoE/demoparser#90]
Fields attacker_name, attacker_steamid is null in player_blind event.

Tested on v0.15.3

Affected demo file:
https://drive.google.com/file/d/1s72gT4GWmHqn_c4Nb2nVQYwP98vC0-uw/view?usp=sharing

Example code:
```
var { parseEvent } = require('@laihoe/demoparser2');

const filePath = process.argv.slice(2)[0];

parsePlayerBlindEvent();

function parsePlayerBlindEvent() {
    let d = parseEvent(filePath, "player_blind")

    d.forEach((e) => {
        if (!e.attacker_steamid) {
            console.log(e);
        }
    });
}
```

**Comment by willbex** [comment]
We didn't see any unusual situation in this demo

**Comment by LaihoE** [comment]
https://github.com/LaihoE/demoparser/pull/202

Fixed here :sweat_smile:
