### ISSUE TITLE
re-check available fields

### ISSUE THREAD

**Issue by LaihoE** [LaihoE/demoparser#92]
some fields in the README don't seem to be working always, examples: Equipment_value_total, money_saved_total, kill_reward_total, cash_earned_total, armor, duck_time_ms, in_crouch, crouch_state, ducked, ducking, jump_time_ms, last_duck_time, team_match_stat

**Comment by captainpd** [comment]
I also encoutered the same issue

**Comment by Tirre** [comment]
The armor value seem to be filled in the 'armor_value' prop rather than 'armor'. 
Whether it's intended or not, I don't know but both are listed in the README

| Prop | Description |
| --- | --- |
| armor | m_iPawnArmor |
| armor_value | m_ArmorValue |

**Comment by LaihoE** [comment]
> The armor value seem to be filled in the 'armor_value' prop rather than 'armor'. Whether it's intended or not, I don't know but both are listed in the README
> 
> Prop	Description
> armor	m_iPawnArmor
> armor_value	m_ArmorValue

Removed armor from readme as armor_value seems to be the new way to go about it
